fail_fast: True
stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
        - id: trailing-whitespace
          stages: [commit, manual]
        - id: end-of-file-fixer
          stages: [commit, manual]
        - id: check-yaml
          stages: [commit, manual]
        - id: check-added-large-files
          stages: [commit, manual]
        - id: check-docstring-first
          stages: [commit, manual]
        # you can enable the following checks if you disable them from drone
        # as drone has credentials in place
        # - id: detect-aws-credentials
        # - id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
        - id: isort
          stages: [commit]
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.7
        stages: [commit]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args: [--config-file, mypy.ini]
        stages: [commit, manual]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
        - id: flake8
          stages: [commit, manual]

-   repo: local
    hooks:
        - id: flakeFunctions
          name: Check for the size of functions
          entry: /usr/bin/flake8 --ignore F,E,W,CFQ002 --max-function-length=20
          types: [python]
          language: script
          stages: [commit]

-   repo: local
    hooks:
      - id: compile
        name: Compile the code
        entry: python -m compileall -q .
        language: system
        stages: [ commit ]

-   repo: local
    hooks:
      - id: runtests
        name: Run unit tests
        entry: pytest tests
        pass_filenames: false
        language: system
        stages: [commit]
